modLoader="javafml"
loaderVersion="[37,)"
license="All Rights Reserved"
[[mods]]
modId="unionlib"
version="${file.jarVersion}"
displayName="UnionLib"
#updateJSONURL="https://raw.githubusercontent.com/Stereowalker/UnionLib/1.16-forge/update.json?token=AIP6TBTIHETPW7EI7336PL3AHEHKG"
#displayURL="https://www.curseforge.com/minecraft/mc-mods/unionlib"
logoFile="pack.png"
credits="I'd like to thank all my supporters on Patreon for giving me a reason to continue modding, and you for downloading and playing with this mod"
authors="Stereowalker"
description='''
A library mod for all my mods
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.unionlib]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[37,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.unionlib]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"