
[magic]
	#The chance a monster will be an abomination when spawned. The higher the value, the rarer the chance. Set to zero to prevent monsters from becoming abominations
	#Range: 0 ~ 10000
	"Abomination Spawn Chance" = 0
	#Disabling this will turn off the affinity system and will allow you to cast spells in every class
	toggle_affinities = true
	#Chances that a mob will drop a scroll when killed by the player. Mob deaths by other causes will be multiplied by 4. The higher the value, the rarer the chance. Set to zero to prevent scrolls from dropping from defeated mobs
	#Range: 0 ~ 100
	"Scroll Drop Chance" = 25

[guns]
	#Disabling this would prevent the guns in this mod from loading in your game
	load_guns = true

[survival]
	#Disabling this will disable any effects from the leveling system
	enable_leveling_system = true

[developerOptions]
	debug_mode = false

