
[thirst]
	#Disabling this will disable this mods thirst system
	"Enable Thirst" = true

[temperature]
	#Disabling this will prevent players from sleeping if they have hyperthermia or hypothermia
	"Enable Hypothermia/Hyperthermia Allow Sleep" = true
	#Disabling this will disable this mods temperature system
	"Enable Temperature" = true

[developerOptions]
	debug_mode = false

